#!/usr/bin/env bash
# Author: Derek Armstrong
# Date: 2022-10-15
# Version: 1.0
# Description: This script will create my base set of VMs
# GitHub: https://github.com/dereklarmstrong/proxmox
#

# This script will create my base set of VMs

# setup help argument
usage="-------------------------------
usage: deploy_base_vm_set.sh -h <help>
-------------------------------
"

# Parse arguments
while getopts "h" opt; do
  case $opt in
    h) echo "$usage"
       exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

# Download the create_vm_full_clone.sh script if it does not exist
if [ ! -f create_vm_full_clone.sh ]; then
  wget https://raw.githubusercontent.com/dereklarmstrong/proxmox/main/scripts/create_vm_full_clone.sh
fi

# Download ssh keys from github
if [ ! -f ~/.ssh/github_rsa.pub ]; then
  wget https://raw.githubusercontent.com/dereklarmstrong/proxmox/main/scripts/download_github_keys.sh
  bash download_github_keys.sh
fi


# Setup VM Deployments
# usage: create_vm_full_clone.sh -s <source_vm_id> -d <destination_vm_id> -n <destination_vm_name> -i <destination_vm_ip_address> -g <destination_vm_gateway> -m <destination_vm_netmask> -h <help>

# dev box setup (homelab range 192.168.1.50-99)
bash create_vm_full_clone.sh -s 9000 -d 201 -n dev1 -i 192.168.1.60
bash create_vm_full_clone.sh -s 9000 -d 202 -n dev2 -i 192.168.1.61

# load balancer setup
bash create_vm_full_clone.sh -s 9000 -d 301 -n lb1 -i 192.168.1.70
bash create_vm_full_clone.sh -s 9000 -d 302 -n lb2 -i 192.168.1.71

# rancher/Kubernetes nodes
bash create_vm_full_clone.sh -s 9000 -d 501 -n rancher-node1 -i 192.168.1.80
bash create_vm_full_clone.sh -s 9000 -d 502 -n rancher-node2 -i 192.168.1.81
bash create_vm_full_clone.sh -s 9000 -d 503 -n rancher-node3 -i 192.168.1.82

# Optional: prepare Kubernetes config for Oracle Linux nodes and deploy
if [ ! -f ../config.k8s.sh ]; then
  cat > ../config.k8s.sh <<'EOF'
# Generated by deploy_base_vm_set.sh
K8S_SSH_USER=opc
K8S_SSH_KEY=~/.ssh/id_rsa
K8S_API_ADVERTISE_ADDRESS="192.168.1.80"
K8S_MASTERS=("192.168.1.80 master1")
K8S_WORKERS=("192.168.1.81 worker1" "192.168.1.82 worker2")
K8S_POD_CIDR="10.244.0.0/16"
K8S_SERVICE_CIDR="10.96.0.0/12"
EOF
  echo "Created ../config.k8s.sh (edit as needed)."
fi

read -p "Run Kubernetes deployment on rancher-node[1-3]? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  bash ./k8s/deploy_ol_k8s_cluster.sh --config ../config.k8s.sh
fi